/**
 * This file is part of the QCAD/CAM software.
 * Do NOT edit this file. Your changes will be lost when the software 
 * is updated or reinstalled. 
 * For details, please refer to the file README.txt in this directory.
 */
include("LaserGrbl.js");

/**
 * Configuration for LaserGrbl controllers.
 * Output in Millimeters.
 */
function LaserGrblMM(documentInterface, camDocumentInterface) {
    LaserGrbl.call(this, documentInterface, camDocumentInterface);

    this.decimals = 3;
    this.unit = RS.Millimeter;
}

LaserGrblMM.prototype = new LaserGrbl();
LaserGrblMM.displayName = "LaserGRBL (offset) [mm]";
