/**
 * This file is part of the QCAD/CAM software.
 * Do NOT edit this file. Your changes will be lost when the software 
 * is updated or reinstalled. 
 * For details, please refer to the file README.txt in this directory.
 */
include("Mach3IN.js");

/**
 * Configuration for Mach3 controllers.
 * Output of offsets in Inches.
 */
function Mach3OffsetIN(documentInterface, camDocumentInterface) {
    Mach3IN.call(this, documentInterface, camDocumentInterface);

    this.outputOffsetPath = true;
}

Mach3OffsetIN.prototype = new Mach3IN();
Mach3OffsetIN.displayName = "Mach3 (Offset) [in]";
