/**
 * This file is part of the QCAD/CAM software.
 * Do NOT edit this file. Your changes will be lost when the software 
 * is updated or reinstalled. 
 * For details, please refer to the file README.txt in this directory.
 */
include("Firecontrol.js");

/**
 * Configuration for Firecontrol controllers.
 * Output in Millimeters.
 */
function FirecontrolMM(documentInterface, camDocumentInterface) {
    Firecontrol.call(this, documentInterface, camDocumentInterface);

    this.decimals = 3;
    this.unit = RS.Millimeter;
}

FirecontrolMM.prototype = new Firecontrol();
FirecontrolMM.displayName = "Firecontrol (offset) [mm]";
