/**
 * This file is part of the QCAD/CAM software.
 * Do NOT edit this file. Your changes will be lost when the software 
 * is updated or reinstalled. 
 * For details, please refer to the file README.txt in this directory.
 */
include("LinuxCNC.js");

function LinuxCNCOffsetIN(cadDocumentInterface, camDocumentInterface) {
    LinuxCNC.call(this, cadDocumentInterface, camDocumentInterface);

    this.decimals = 4;
    this.unit = RS.Inch;
    this.outputOffsetPath = true;
}

LinuxCNCOffsetIN.prototype = new LinuxCNC();

LinuxCNCOffsetIN.displayName = "LinuxCNC (Offset) [in]";
