/**
 * This file is part of the QCAD/CAM software.
 * Do NOT edit this file. Your changes will be lost when the software 
 * is updated or reinstalled. 
 * For details, please refer to the file README.txt in this directory.
 */
include("LinuxCNC.js");

function LinuxCNCMM(cadDocumentInterface, camDocumentInterface) {
    LinuxCNC.call(this, cadDocumentInterface, camDocumentInterface);

    this.decimals = 4;
    this.unit = RS.Millimeter;
}

LinuxCNCMM.prototype = new LinuxCNC();

LinuxCNCMM.displayName = "LinuxCNC [mm]";
