/**
 * This file is part of the QCAD/CAM software.
 * Do NOT edit this file. Your changes will be lost when the software 
 * is updated or reinstalled. 
 * For details, please refer to the file README.txt in this directory.
 */
include("Mach3MM.js");

/**
 * Configuration for Mach3 controllers.
 * Output of offsets in Millimeters.
 */
function Mach3OffsetMM(documentInterface, camDocumentInterface) {
    Mach3MM.call(this, documentInterface, camDocumentInterface);

    this.outputOffsetPath = true;
}

Mach3OffsetMM.prototype = new Mach3MM();
Mach3OffsetMM.displayName = "Mach3 (Offset) [mm]";
