/**
 * This file is part of the QCAD/CAM software.
 * Do NOT edit this file. Your changes will be lost when the software 
 * is updated or reinstalled. 
 * For details, please refer to the file README.txt in this directory.
 */
include("Mach3MM.js");

/**
 * Configuration for Mach3 controllers.
 * Output of offsets in Millimeters.
 */
function UA481(documentInterface, camDocumentInterface) {
    Mach3MM.call(this, documentInterface, camDocumentInterface);

    this.outputOffsetPath = true;
}

 UA481.prototype = new Mach3MM();
 UA481.displayName = "UA-481";
